-- 数据库
DROP DATABASE IF EXISTS SixBox;
CREATE DATABASE SixBox;
USE SixBox;

-- 测试表
DROP TABLE IF EXISTS test;
CREATE TABLE test (
  id         INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  title      VARCHAR(255)        NOT NULL UNIQUE,
  content    VARCHAR(255),
  createTime DATETIME
)
  DEFAULT CHARSET = utf8;
